version: 1
# Formatters
formatters:
  simple:
    format: '%(levelname)s: %(message)s'
  verbose:
    format: '%(asctime)s: %(name)s - %(levelname)s : %(message)s'
# Filters

# Handlers
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
  logfile:
    class: logging.FileHandler
    formatter: verbose
    level: DEBUG
    filename: 'default.log'

# Loggers
loggers:
  page_loader:
    level: ERROR
    handlers: 
      [logfile, console]