[tool.poetry]
name = "page-loader"
version = "0.1.0"
description = "Tool for downloding web-pages to local machine"
authors = ["Artem Stepanenko <artem.stepanenko.ks.ua@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
flake8 = "^3.7.9"
wemake-python-styleguide = "^0.13.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
