name: Build

on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8]
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1    
    - name: setup python versions
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install  poetry
        poetry install
    - name: run scripts
      run: |
        make lint
        make test
        make coverage
    - name: upload test coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: pytest
        name: codecov-umbrella
        fail_ci_if_error: true 
