name: Build

on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8]
        os: [ubuntu-16.04, ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1    
    - name: setup python versions
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install  poetry
        poetry install
    - name: before script
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    - name: run scripts
      run: |
        make lint
        make test
        make test-cov2xml
    - name: upload test coverage
      uses: codecov/codecov-action@v1
      with:
        # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: ./coverage.xml # optional
        flags: pytest # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
